name: Docker Image CI

on:
  # Manually triggered
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd ui && docker build . --tag auscopeappstore:$(date +%s) --file docker/Dockerfile 
      # docker build . --file Dockerfile --tag auscopeappstore:$(date +%s)
